### PR TITLE
Check no-cache flag

### PR DESCRIPTION
**Pull request by wsargent**
Fix for https://github.com/playframework/cachecontrol/issues/35

### CODE REVIEW

**Comment by marcospereira** [comment]
Hey @wsargent, quick question: is this redundant with #32?

**Comment by wsargent** [comment]
@marcospereira we can close #32 out since this is merged already.

**Comment by wsargent** [comment]
I will need to update with a patch for the `Validate` case here https://github.com/playframework/cachecontrol/pull/32#issuecomment-450283305.  I'll do that now.

**Comment by wsargent** [comment]
Validate case is correct, no change needed.

**Comment by bpossolo** [comment]
it would have been nice for the commit message to at least give credit for having found the bug and submitted the suggested fix.

**Pull request merged**
